Music_App/config/routes.rb
Rails.application.routes.draw do
  get 'bands/new'

  get 'bands/create'

  get 'bands/edit'

  get 'bands/show'

  get 'bands/update'

  get 'bands/destroy'

  get 'bands/index'

  resources :users#, only: [:create, :new, :show]
  resources :session#, only: [:create, :new, :destroy]
  resources :bands
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Music_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Music_App/app/models/band.rb
class Band < ApplicationRecord
  validates :name, null: false

    def new
    end

    def create
    end

    def edit
    end

    def destroy
    end
end

Music_App/app/models/user.rb
class User < ApplicationRecord
  validates :session_token, :email, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  has_many :bands

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

Music_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session_token[:session_token])
  end
end

Music_App/app/controllers/bands_controller.rb
class BandsController < ApplicationController


  def new
    @bands = Band.new
    render :new
  end

  def create

  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  def index
  end
end

Music_App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login(@user)
      redirect_to users_url
    else
      flash[:errors] = ["Invalid login credentials"]
      render :new
  end

  def destroy
    current_user.logout
    redirect_to new_session_url
  end
end

Music_App/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

Music_App/app/helpers/application_helper.rb
module ApplicationHelper



end

Music_App/app/helpers/bands_helper.rb
module BandsHelper
end

Music_App/app/helpers/sessions_helper.rb
module SessionsHelper
end

Music_App/app/helpers/users_helper.rb
module UsersHelper
end

Music_App/app/views/bands/create.html.erb
<h1>Bands#create</h1>
<p>Find me in app/views/bands/create.html.erb</p>

Music_App/app/views/bands/destroy.html.erb
<h1>Bands#destroy</h1>
<p>Find me in app/views/bands/destroy.html.erb</p>

Music_App/app/views/bands/edit.html.erb
<h1>Bands#edit</h1>
<p>Find me in app/views/bands/edit.html.erb</p>

Music_App/app/views/bands/index.html.erb
<h1>Bands#index</h1>
<p>Find me in app/views/bands/index.html.erb</p>

Music_App/app/views/bands/new.html.erb
<h1>Bands - New</h1>
<form action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label>Name:
    <input type="text" name="" value="">
  </label>
<br>
  <input type="submit" value="Sign Up">
</form>

Music_App/app/views/bands/show.html.erb
<h1>Bands#show</h1>
<p>Find me in app/views/bands/show.html.erb</p>

Music_App/app/views/bands/update.html.erb
<h1>Bands#update</h1>
<p>Find me in app/views/bands/update.html.erb</p>

Music_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    MUSIC APP
    <% if logged_in? %>
      <%= current_user.email %>
      <%= button_to  "Logout", session_url, method: :delete%>
    <% else %>
      <%= link_to "Sign In", new_session_url %>
      <%= link_to "Sign Up", new_session_url %>
    <% end %>
  </header>

  <div class="errors">
    <ul>
      <% flash[:errors].try(:each) do |err| %>
        <li><%= err %></li>
      <% end %>
    </ul>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

Music_App/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

Music_App/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

Music_App/app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
   <li>Name: <%= user.name %></li>
  <% end %>
</ul>

Music_App/app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label>Email:
    <input type="text" name="user[email]">
  </label>
<br>
  <label>Password:
    <input type="text" name="user[password]">
  </label>
<br>
  <input type="submit" value="Sign Up">
</form>

Music_App/app/views/users/show.html.erb
<h1><(o . O <  )</h1>

<%= @user.emai %>

Music_App/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

Music_App/app/views/users/user_params.html.erb
<h1>Users#user_params</h1>
<p>Find me in app/views/users/user_params.html.erb</p>